# Generated by Django 6.0.2 on 2026-02-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_gastoextra_ventasalteña'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventasalteña',
            name='baja',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventasalteña',
            name='entrada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventasalteña',
            name='produccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventasalteña',
            name='traspaso',
            field=models.CharField(choices=[('Dest', 'Sin Traspaso'), ('Calacoto', 'Sucursal Calacoto'), ('Mendez', 'Sucursal Méndez Arcos'), ('San Pedro', 'Sucursal San Pedro')], default='Dest', max_length=20),
        ),
    ]
