# Generated by Django 6.0.2 on 2026-02-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_ventasalteña_baja_ventasalteña_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventasalteña',
            name='traspaso',
            field=models.CharField(choices=[('Dest', 'Ninguno'), ('Calacoto', 'Calacoto'), ('Mendez', 'Méndez Arcos'), ('San Pedro', 'San Pedro')], default='Dest', max_length=20),
        ),
    ]
