# Generated by Django 6.0.2 on 2026-02-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_ventasalteña_traspaso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventasalteña',
            name='baja',
        ),
        migrations.RemoveField(
            model_name='ventasalteña',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='ventasalteña',
            name='produccion',
        ),
        migrations.RemoveField(
            model_name='ventasalteña',
            name='traspaso',
        ),
    ]
