# Generated by Django 6.0.2 on 2026-02-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_ventasalteña_baja_remove_ventasalteña_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoextra',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
