# Generated by Django 6.0.2 on 2026-02-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_gastoextra_descripcion_alter_gastoextra_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoextra',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (Bs)'),
        ),
    ]
