# Generated by Django 6.0.2 on 2026-02-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_gastoextra_descripcion_alter_gastoextra_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajadiaria',
            name='personal_turno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='traspaso_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
